import type { Metadata } from 'next';
import { Geist, Geist_Mono, Mulish } from 'next/font/google';

import { ThemeProvider } from '../../../providers/ThemeProvider';
import { ApolloClientProvider } from '~/providers/apollo-client-provider/apolloClientProvider';
import EmotionProvider from '~/providers/EmotionProvider';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin']
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin']
});

const mulish = Mulish({
  subsets: ['latin', 'cyrillic'],
  weight: ['400', '700'],
  variable: '--font-mulish'
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function BodyProvider({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable} ${mulish.variable}`}>
      <body className={`${geistSans.variable} ${geistMono.variable} ${mulish.variable}`}>
        <EmotionProvider>
          <ThemeProvider>
            <ApolloClientProvider>{children}</ApolloClientProvider>
          </ThemeProvider>
        </EmotionProvider>
      </body>
    </html>
  );
}
