import type { Metadata } from 'next';
import { Mulish, Oswald } from 'next/font/google';

import { ThemeProvider } from '../../../providers/ThemeProvider';
import { ApolloClientProvider } from '~/providers/apollo-client-provider/apolloClientProvider';
import EmotionProvider from '~/providers/EmotionProvider';

const mulish = Mulish({
  subsets: ['latin', 'cyrillic'],
  weight: ['400', '500', '600', '700'],
  variable: '--font-mulish',
  display: 'swap'
});

const oswald = Oswald({
  subsets: ['latin', 'cyrillic'],
  weight: ['400', '600', '700'],
  variable: '--font-oswald',
  display: 'swap'
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function BodyProvider({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${mulish.variable} ${oswald.variable}`} suppressHydrationWarning>
      <body suppressHydrationWarning>
        <EmotionProvider>
          <ThemeProvider>
            <ApolloClientProvider>{children}</ApolloClientProvider>
          </ThemeProvider>
        </EmotionProvider>
      </body>
    </html>
  );
}
