import './globals.css';
import { Container } from '@mui/material';
import type { Metadata } from 'next';
import { Geist, Geist_Mono, Mulish } from 'next/font/google';

import { ReactQueryProvider } from '~/components/react-query-provider/reactQeryProvider';
import { SideBarNavgation } from '~/components/side-navigation/SideNavigation';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin']
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin']
});

const mulish = Mulish({
  subsets: ['latin', 'cyrillic'],
  weight: ['400', '700'],
  variable: '--font-mulish'
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} ${mulish.variable}`}>
        <ReactQueryProvider>
          <SideBarNavgation />
          <Container maxWidth="md" sx={{ border: '1px solid #ccc', padding: '20px' }}>
            {children}
          </Container>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
