query AllFunds($filters: FundFiltersInput) {
  findAllFunds(filters: $filters) {
    id
    fundNumber
    name {
      uk
      en
    }
    documentCreationDate {
      uk
      en
    }
    chronologicalBoundaries {
      uk
      en
    }
    casesCount
    descriptionsCount
    status
    updatedAt
  }
}

query FundById($id: ID!) {
  findFundById(id: $id) {
    id
    fundNumber
    name {
      uk
      en
    }
    documentCreationDate {
      uk
      en
    }
    chronologicalBoundaries {
      uk
      en
    }
    organizationForm {
      uk
      en
    }
    description {
      uk
      en
    }
    casesCount
    descriptionsCount
    status
    createdAt
    updatedAt
  }
}

query PaginatedFunds($page: Int!, $limit: Int!, $filters: FundFiltersInput) {
  findFundsPaginated(page: $page, limit: $limit, filters: $filters) {
    items {
      id
      fundNumber
      name {
        uk
        en
      }
      documentCreationDate {
        uk
        en
      }
      chronologicalBoundaries {
        uk
        en
      }
      casesCount
      descriptionsCount
      status
      updatedAt
    }
    total
    page
    totalPages
  }
}
