fragment MediaMentionFields on MediaMention {
  id
  url
  adminTitle
  title { uk en }
  description { uk en }
  keywords { uk en }
  allowIndexation { uk en }
  coverImage {
    src { uk en }
    alt { uk en }
    crop { x y width height }
  }
  slug
  status
  publishedAt
  createdAt
  updatedAt
  meta { views }
}

query MediaMentionById($id: ID!) {
  mediaMentionById(id: $id) {
    ...MediaMentionFields
  }
}

query MediaMentionBySlug($slug: String!) {
  mediaMentionBySlug(slug: $slug) {
    ...MediaMentionFields
  }
}

query AllMediaMentions($filters: MediaMentionsFiltersInput) {
  allMediaMentions(filters: $filters) {
    ...MediaMentionFields
  }
}

query PublishedMediaMentions($filters: MediaMentionsFiltersInput) {
  publishedMediaMentions(filters: $filters) {
    ...MediaMentionFields
  }
}

query PaginatedMediaMentions($page: Int = 1, $limit: Int = 10, $filters: MediaMentionsFiltersInput) {
  paginatedMediaMentions(page: $page, limit: $limit, filters: $filters) {
    items {
      ...MediaMentionFields
    }
    total
    page
    totalPages
  }
}

query MediaMentionsCount($status: MediaStatus) {
  mediaMentionsCount(status: $status)
}