query OpusById($id: ID!) {
  opusById(id: $id) {
    id
    number
    numberKind
    title {
      uk
      en
    }
    releaseYear
    name {
      uk
      en
    }
    additionalText
    creationYear
    endYear
    datesNote
    genre
    adminTitle
    slug
    status
    description {
      uk
      en
    }
    parts {
      uk
      en
    }
    introDescription {
      uk
      en
    }
    keywords {
      uk
      en
    }
    allowIndexation {
      uk
      en
    }
    coverImage {
      src
      alt {
        uk
        en
      }
      crop {
        x
        y
        width
        height
      }
    }
    gallery {
      id
      src
      description {
        uk
        en
      }
      altText {
        uk
        en
      }
      crop {
        x
        y
        width
        height
      }
    }
    performancesTitle {
      uk
      en
    }
    performances {
      id
      title {
        uk
        en
      }
      videoUrl
    }
    compositions {
      id
      opusId
      title {
        uk
        en
      }
      year
      genre
      audioAvailable
      sheetAvailable
      sheetMusic {
        url
        name
        publishDate
        isFree
        dateUploaded
      }
      audios {
        name
        url
      }
    }
    publishedAt
    createdAt
    updatedAt

    introDescription {
      uk
      en
    }
    gallery {
      id
      src
      description {
        uk
        en
      }
      altText {
        uk
        en
      }
      crop {
        x
        y
        width
        height
      }
    }
    performances {
      id
      title {
        uk
        en
      }
      videoUrl
    }
  }
}

query AllOpuses($filters: OpusFiltersInput) {
  allOpuses(filters: $filters) {
    id
    number
    numberKind
    title {
      uk
      en
    }
    releaseYear
    genre
    status
    updatedAt
    createdAt
  }
}

query SearchCompositions($search: String!) {
  searchCompositions(search: $search) {
    id
    opusId
    title {
      uk
      en
    }
    year
    genre
    audioAvailable
    sheetAvailable
    sheetMusic {
      url
      name
      publishDate
      isFree
      dateUploaded
    }
    audios {
      name
      url
    }
  }
}
