query OpusById($id: ID!) {
  opusById(id: $id) {
    id
    number
    numberKind
    title {
      uk
      en
    }
    releaseYear
    name {
      uk
      en
    }
    additionalText
    creationYear
    endYear
    datesNote
    genre
    adminTitle
    slug
    status
    description {
      uk
      en
    }
    parts {
      uk
      en
    }
    introDescription {
      uk
      en
    }
    keywords {
      uk
      en
    }
    allowIndexation {
      uk
      en
    }
    coverImage {
      src
      alt {
        uk
        en
      }
      crop {
        x
        y
        width
        height
      }
    }
    gallery {
      id
      src
      description {
        uk
        en
      }
      altText {
        uk
        en
      }
      crop {
        x
        y
        width
        height
      }
    }
    performancesTitle {
      uk
      en
    }
    performances {
      id
      title {
        uk
        en
      }
      videoUrl
    }
    compositions {
      id
      opusId
      title {
        uk
        en
      }
      year
      order
      genre
      audioAvailable
      sheetAvailable
      sheetMusic {
        url
        name
        publishDate
        isFree
        dateUploaded
      }
      audios {
        name
        url
      }
    }
    publishedAt
    createdAt
    updatedAt
  }
}

query PaginatedWorks($tab: WorksTab, $filters: WorksFiltersInput) {
  paginatedWorks(tab: $tab, filters: $filters) {
    total
    page
    totalPages

    groups {
      id
      number
      numberKind
      name {
        uk
        en
      }
      genre
      status
      creationYear
      endYear
      updatedAt
      createdAt
      compositions {
        id
        title {
          uk
          en
        }
      }
    }

    works {
      id
      title {
        uk
        en
      }
      genre
      status
      year
      updatedAt
      createdAt
    }
  }
}

query SearchCompositions($search: String!) {
  searchCompositions(search: $search) {
    id
    opusId
    title {
      uk
      en
    }
    year
    genre
    audioAvailable
    sheetAvailable
    sheetMusic {
      url
      name
      publishDate
      isFree
      dateUploaded
    }
    audios {
      name
      url
    }
  }
}
