mutation CreateComposition($input: CreateCompositionInput!) {
  createComposition(input: $input) {
    id
    name {
      uk
      en
    }
    genre
    year
    audioAvailable
    sheetAvailable
    audios {
      name
      url
    }
    sheetMusic {
      name
      fileName
      url
      publishDate
      isFree
      dateUploaded
    }
    createdAt
    updatedAt
  }
}

mutation UpdateComposition($id: ID!, $input: UpdateCompositionInput!) {
  updateComposition(id: $id, input: $input) {
    id
    name {
      uk
      en
    }
    genre
    year
    audioAvailable
    sheetAvailable
    audios {
      name
      url
    }
    sheetMusic {
      name
      fileName
      url
      publishDate
      isFree
      dateUploaded
    }
    createdAt
    updatedAt
  }
}

mutation DeleteComposition($id: ID!) {
  deleteComposition(id: $id)
}
