mutation CreateFond($input: CreateFondInput!) {
  createFond(input: $input) {
    id
    fondNumber
    name {
      uk
      en
    }
    status
    createdAt
    updatedAt
  }
}

mutation UpdateFond($id: ID!, $input: UpdateFondInput!) {
  updateFond(id: $id, input: $input) {
    id
    fondNumber
    name {
      uk
      en
    }
    documentCreationDate {
      uk
      en
    }
    chronologicalBoundaries {
      uk
      en
    }
    organizationForm {
      uk
      en
    }
    description {
      uk
      en
    }
    status
    updatedAt
  }
}

mutation DeleteFond($id: ID!) {
  deleteFond(id: $id)
}