mutation CreateMediaMention($input: CreateMediaMentionInput!) {
  createMediaMention(input: $input) {
    id
    url
    adminTitle
    slug
    status
    title { uk en }
    description { uk en }
    keywords { uk en }
    allowIndexation { uk en }
    coverImage {
      src
      alt { uk en }
      caption { uk en }
      crop { x y width height }
    }
    publishedAt
    createdAt
    updatedAt
    meta { views }
  }
}

mutation UpdateMediaMention($id: ID!, $input: UpdateMediaMentionInput!) {
  updateMediaMention(id: $id, input: $input) {
    id
    url
    adminTitle
    slug
    status
    title { uk en }
    description { uk en }
    keywords { uk en }
    allowIndexation { uk en }
    coverImage {
      src
      alt { uk en }
      caption { uk en }
      crop { x y width height }
    }
    publishedAt
    createdAt
    updatedAt
    meta { views }
  }
}

mutation AddMediaMentionView($id: ID!) {
  addMediaMentionView(id: $id)
}

mutation DeleteMediaMention($id: ID!) {
  deleteMediaMention(id: $id)
}