mutation CreateNews($input: CreateNewsInput!) {
  createNews(input: $input) {
    id
    adminTitle
    title {
      uk
      en
    }
    slug
    status
    newsDate
    publishedAt
    createdAt
  }
}

mutation UpdateNews($id: ID!, $input: UpdateNewsInput!) {
  updateNews(id: $id, input: $input) {
    id
    adminTitle
    title {
      uk
      en
    }
    slug
    description {
      uk
      en
    }
    status
    newsDate
    updatedAt
  }
}

mutation DeleteNews($id: ID!) {
  deleteNews(id: $id)
}

mutation IncrementNewsViews($id: ID!) {
  incrementNewsViews(id: $id) {
    id
    meta {
      views
    }
  }
}