mutation CreateOpus($input: CreateOpusInput!) {
  createOpus(input: $input) {
    id
    number
    numberKind
    title {
      uk
      en
    }
    createdAt
  }
}

mutation UpdateOpus($id: ID!, $input: UpdateOpusInput!) {
  updateOpus(id: $id, input: $input) {
    id
    number
    numberKind
    title {
      uk
      en
    }
    name {
      uk
      en
    }
    additionalText
    creationYear
    endYear
    datesNote
    genre
    status
    compositions {
      id
      order
      title {
        uk
        en
      }
      genre
      year
      audios {
        name
        url
      }
      sheetMusic {
        name
        url
        publishDate
      }
    }
    introDescription {
      uk
      en
    }
    parts {
      uk
      en
    }
    gallery {
      id
      src
      description {
        uk
        en
      }
      altText {
        uk
        en
      }
      crop {
        x
        y
        width
        height
      }
    }
    performancesTitle {
      uk
      en
    }
    performances {
      id
      title {
        uk
        en
      }
      videoUrl
    }
    updatedAt
  }
}

mutation DeleteOpus($id: ID!) {
  deleteOpus(id: $id)
}
