mutation CreateOpus($input: CreateOpusInput!) {
  createOpus(input: $input) {
    id
    number
    numberKind
    name {
      uk
      en
    }
    createdAt
  }
}

mutation UpdateOpus($id: ID!, $input: UpdateOpusInput!) {
  updateOpus(id: $id, input: $input) {
    id
    number
    numberKind
    blocksOrder
    title {
      uk
      en
    }
    name {
      uk
      en
    }
    additionalText
    creationYear
    endYear
    datesNote
    genre {
      uk
      en
    }
    status
    compositions {
      id
      name {
        uk
        en
      }
      genre
      year
      audios {
        name
        url
      }
      sheetMusic {
        name
        fileName
        url
        publishDate
      }
    }
    introDescription {
      uk
      en
    }
    parts {
      uk
      en
    }
    gallery {
      id
      src
      description {
        uk
        en
      }
      altText {
        uk
        en
      }
      crop {
        x
        y
        width
        height
      }
    }
    performancesTitle {
      uk
      en
    }
    performances {
      id
      title {
        uk
        en
      }
      videoUrl
    }
    updatedAt
  }
}

mutation DeleteOpus($id: ID!) {
  deleteOpus(id: $id)
}

mutation UpdateOpusStatus($id: ID!, $status: OpusStatus!) {
  updateOpusStatus(id: $id, status: $status) {
    id
    status
  }
}

mutation UnlinkComposition($opusId: ID!, $compositionId: ID!) {
  unlinkComposition(opusId: $opusId, compositionId: $compositionId) {
    id
    number
    numberKind
    name {
      uk
      en
    }
    genre {
      uk
      en
    }
    status
    creationYear
    endYear
    updatedAt
    createdAt
    compositions {
      id
      name {
        uk
        en
      }
    }
  }
}
