mutation CreateOpus($input: CreateOpusInput!) {
  createOpus(input: $input) {
    id
    number
    numberKind
    title {
      uk
      en
    }
    createdAt
  }
}

mutation UpdateOpus($id: ID!, $input: UpdateOpusInput!) {
  updateOpus(id: $id, input: $input) {
    id
    number
    numberKind
    title {
      uk
      en
    }
    introDescription {
      uk
      en
    }
    parts {
      uk
      en
    }
    gallery {
      id
      src
      description {
        uk
        en
      }
      altText {
        uk
        en
      }
      crop {
        x
        y
        width
        height
      }
    }
    updatedAt
  }
}

mutation DeleteOpus($id: ID!) {
  deleteOpus(id: $id)
}
