union LoginResult = LoginPayload | ErrorPayload

type Mutation {
  login(email: String!, password: String!): LoginResult!
  logout: Boolean!
  refreshToken: RefreshTokenPayload!
}

type LoginPayload {
  success: Boolean!
  adminId: ID
  adminType: String
}

type RefreshTokenPayload {
  success: Boolean!
}

type ErrorPayload {
  success: Boolean!
  message: String!
  statusCode: Int!
}
scalar JSON

type Page {
  id: ID!
  slug: String!
  title: LocalizedString!
  status: String!
  pageType: String!
  blocks: JSON!
  createdAt: String!
  updatedAt: String!
}

type LocalizedString {
  uk: String
  en: String
}

type Query {
  _empty: String
  test: RefreshTokenPayload!
  pageBlocks(slug: String!): Page
}
