enum AssetType {
  image
  pdf
  audio
  document
  spreadsheet
  video
  archive
}

enum AssetSortBy {
  createdAt
  updatedAt
  filename
}

type AssetUsageRef {
  pageId: String
  blockId: String
  locale: String
}

type Asset {
  id: ID!
  type: AssetType!
  tags: [String!]!
  usageRefs: [AssetUsageRef!]!
  filename: String!
  originalname: String
  mimeType: String!
  sizeBytes: Int!
  url: String!
  createdBy: String
  description: String
  isStarred: Boolean!
  createdAt: String!
  updatedAt: String!
}

input AssetsFiltersInput {
  type: AssetType
  isStarred: Boolean
  isUsed: Boolean
  tag: String
  search: String
  sortBy: AssetSortBy
  sortOrder: SortOrder
  limit: Int
  skip: Int
}

extend type Query {
  allAssets(filters: AssetsFiltersInput): [Asset!]!
}

input UpdateAssetInput {
  isStarred: Boolean
  filename: String
  description: String
}

input CreateAssetInput {
  filename: String!
  originalname: String
  mimeType: String!
  sizeBytes: Int!
  url: String!
  type: String! # 'image', 'audio', 'document', 'archive', etc.
  description: String
}

extend type Mutation {
  updateAsset(id: ID!, input: UpdateAssetInput!): Asset!
  createAsset(input: CreateAssetInput!): Asset!
  deleteAsset(id: ID!): Boolean!
}
