type Query {
  _empty: String
  test: RefreshTokenPayload!
}

type Mutation {
  _empty: String
}

type LocalizedJSON {
  uk: JSON!
  en: JSON!
}

type LocalizedString {
  uk: String!
  en: String!
}

type LocalizedBoolean {
  uk: Boolean!
  en: Boolean!
}

type CropRect {
  x: Float!
  y: Float!
  width: Float!
  height: Float!
}

type LocalizedImage {
  src: String!
  alt: LocalizedString!
  caption: LocalizedString!
  isTmp: Boolean
  crop: CropRect
}

type ContentMeta {
  views: Int!
}

interface BaseContent {
  adminTitle: String!
  title: LocalizedString!
  description: LocalizedString!
  keywords: LocalizedString!
  allowIndexation: LocalizedBoolean!
  slug: String!
  coverImage: LocalizedImage!
  meta: ContentMeta!
  publishedAt: String
  createdAt: String!
  updatedAt: String!
}

enum SortOrder {
  asc
  desc
}

enum ContentLanguage {
  uk
  en
  bilingual
}

input SortOptions {
  field: String!
  order: SortOrder!
}
