type CompositionSheetMusic {
  url: String
  name: String
  publishDate: String
  isFree: Boolean
  dateUploaded: String
}

type CompositionAudio {
  name: String!
  url: String!
}

type Composition {
  id: ID!
  name: LocalizedString!
  year: Int
  genre: String
  audioAvailable: Boolean
  sheetAvailable: Boolean
  sheetMusic: [CompositionSheetMusic!]
  audios: [CompositionAudio!]
  createdAt: String!
  updatedAt: String!
}

extend type Query {
  compositionById(id: ID!): Composition
}

input CompositionSheetMusicInput {
  url: String
  name: String
  publishDate: String
  isFree: Boolean
  dateUploaded: String
}

input CompositionAudioInput {
  name: String!
  url: String!
}

input CreateCompositionInput {
  name: JSON
  year: Int
  genre: String
  audioAvailable: Boolean
  sheetAvailable: Boolean
  sheetMusic: [CompositionSheetMusicInput!]
  audios: [CompositionAudioInput!]
}

input UpdateCompositionInput {
  name: JSON
  year: Int
  genre: String
  audioAvailable: Boolean
  sheetAvailable: Boolean
  sheetMusic: [CompositionSheetMusicInput!]
  audios: [CompositionAudioInput!]
}

extend type Mutation {
  createComposition(input: CreateCompositionInput!): Composition!
  updateComposition(id: ID!, input: UpdateCompositionInput!): Composition!
  deleteComposition(id: ID!): Boolean!
}
