enum FondStatus {
  draft
  published
  hidden
  archived
  editing
}

input CreateFondInput {
    fondNumber: Int!
    name: JSON!
    documentCreationDate: JSON!
    chronologicalBoundaries: JSON
    organizationForm: JSON 
    description: JSON 
    status: FondStatus
}

type Fond {
    id: ID!
    fondNumber: Int!
    name: LocalizedString!
    documentCreationDate: LocalizedString!
    chronologicalBoundaries: LocalizedString
    organizationForm: LocalizedString 
    description: LocalizedString 
    status: FondStatus!
    updatedAt: String! 
    createdAt: String!
}

type PaginatedFonds {
    items: [Fond!]!
    total: Int!
    page: Int!
    totalPages: Int!
}

input FondFiltersInput {
    limit: Int
    skip: Int
    slug: String
    search: String
    languages: [ContentLanguage!]
    sort: [SortOptions!]
}

input UpdateFondInput {
    fondNumber: Int
    name: JSON
    documentCreationDate: JSON
    chronologicalBoundaries: JSON
    organizationForm: JSON 
    description: JSON 
    status: FondStatus
}

input DeleteFondInput {
    fondNumber: Int!
}

extend type Query {
    findFondById(id: ID!): Fond
    findAllFonds(filters: FondFiltersInput): [Fond!]
    findFondsPaginated(
        page: Int!,
        limit: Int!,
        filters: FondFiltersInput
    ): PaginatedFonds
}

extend type Mutation {
    createFond(input: CreateFondInput!): Fond!
    updateFond(id: ID!, input: UpdateFondInput!): Fond!
    deleteFond(id: ID!): Boolean!
}