enum MediaStatus {
  draft
  published
  hidden
  archived
  editing
}

type MediaMention implements BaseContent {
  id: ID!
  url: String!
  adminTitle: String!
  title: LocalizedString!
  slug: String!
  description: LocalizedString!
  keywords: LocalizedString!
  coverImage: LocalizedImage!
  status: MediaStatus!
  allowIndexation: LocalizedBoolean!
  publishedAt: String
  createdAt: String!
  updatedAt: String!
  meta: ContentMeta!
}

type PaginatedMediaMentions {
  items: [MediaMention!]!
  total: Int!
  page: Int!
  totalPages: Int!
}

input MediaMentionsFiltersInput {
  status: MediaStatus
  limit: Int
  skip: Int
  slug: String
  sort: [SortOptions!]
}

input CreateMediaMentionInput {
  url: String!
  adminTitle: String!
  title: JSON!
  description: JSON!
  keywords: JSON!
  allowIndexation: JSON!
  coverImage: JSON!
  status: MediaStatus
  publishedAt: String
}

input CoverImageInput {
  src: String!
  alt: String
  width: Int
  height: Int
}

input UpdateMediaMentionInput {
  url: String # Will need to re-fetch metadata if URL is changed
  adminTitle: String
  title: JSON
  description: JSON
  keywords: JSON
  allowIndexation: JSON
  coverImage: JSON
  slug: String
  status: MediaStatus
  publishedAt: String
}

extend type Query {
  mediaMentionById(id: ID!): MediaMention
  mediaMentionBySlug(slug: String!): MediaMention
  allMediaMentions(filters: MediaMentionsFiltersInput): [MediaMention!]!
  publishedMediaMentions(filters: MediaMentionsFiltersInput): [MediaMention!]!
  paginatedMediaMentions(page: Int!, limit: Int!, filters: MediaMentionsFiltersInput): PaginatedMediaMentions!
  mediaMentionsCount(status: MediaStatus): Int!
}

extend type Mutation {
  createMediaMention(input: CreateMediaMentionInput!): MediaMention!
  updateMediaMention(id: ID!, input: UpdateMediaMentionInput!): MediaMention!
  addMediaMentionView(id: ID!): Int!
  deleteMediaMention(id: ID!): Boolean!
}
