enum OpusStatus {
  draft
  published
}

enum OpusNumberKind {
  op
  sineop
  compositions
}

enum WorksTab {
  all
  op
  sineop
  compositions
}

enum WorksSortBy {
  number
  createdAt
  updatedAt
  publishedAt
}

type OpusGalleryItem {
  id: ID!
  src: String!
  description: LocalizedString
  altText: LocalizedString
  crop: CropRect
}

type OpusPerformance {
  id: ID!
  title: LocalizedString
  videoUrl: String
}

type Opus {
  id: ID!
  number: Float!
  numberKind: OpusNumberKind!
  title: LocalizedString!
  releaseYear: Int
  name: LocalizedString!
  additionalText: String
  creationYear: String!
  endYear: String
  datesNote: String
  genre: String
  adminTitle: String
  slug: String
  description: LocalizedString
  introDescription: LocalizedString
  parts: LocalizedString
  keywords: LocalizedString
  coverImage: LocalizedImage

  gallery: [OpusGalleryItem!]
  performancesTitle: LocalizedString
  performances: [OpusPerformance!]

  allowIndexation: LocalizedBoolean
  status: OpusStatus
  compositions: [Composition!]
  createdAt: String!
  updatedAt: String!
  publishedAt: String
  meta: ContentMeta
}

type PaginatedWorks {
  groups: [Opus!]!
  works: [Composition!]!

  total: Int!
  page: Int!
  totalPages: Int!
}

input WorksSortOptions {
  field: WorksSortBy!
  order: SortOrder!
}

input WorksFiltersInput {
  statuses: [OpusStatus]
  languages: [ContentLanguage]
  search: String
  limit: Int
  skip: Int
  sort: [WorksSortOptions!]
}

input CreateOpusInput {
  numberKind: OpusNumberKind
  number: Float
  name: JSON
  additionalText: String
  creationYear: String
  endYear: String
  datesNote: String
  genre: String
  compositions: JSON
  adminTitle: String
  title: JSON!
  description: JSON
  introDescription: JSON
  parts: JSON
  gallery: JSON
  performancesTitle: JSON
  performances: JSON
  keywords: JSON
  allowIndexation: JSON
  coverImage: JSON
  status: OpusStatus
  publishedAt: String
}

input UpdateOpusInput {
  numberKind: OpusNumberKind
  number: Float
  name: JSON
  additionalText: String
  creationYear: String
  endYear: String
  datesNote: String
  genre: String
  compositions: JSON
  adminTitle: String
  title: JSON
  description: JSON
  introDescription: JSON
  parts: JSON
  gallery: JSON
  performancesTitle: JSON
  performances: JSON
  keywords: JSON
  allowIndexation: JSON
  coverImage: JSON
  status: OpusStatus
  publishedAt: String
}

extend type Query {
  opusById(id: ID!): Opus
  opusByNumber(number: Float!): Opus
  searchCompositions(search: String!): [Composition!]!
  paginatedWorks(tab: WorksTab, filters: WorksFiltersInput): PaginatedWorks!
  opusesCount(status: OpusStatus): Int!
}

extend type Mutation {
  createOpus(input: CreateOpusInput!): Opus!
  updateOpus(id: ID!, input: UpdateOpusInput!): Opus!
  deleteOpus(id: ID!): Boolean!
}
