name: Changelog

on:
  workflow_dispatch:
  workflow_call:

permissions:
  contents: read  
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest

    permissions:
      contents: write   
      pull-requests: write  

    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          token: ${{ github.token }}
          release-type: simple
  
  comment:
    name: Comment on PR
    uses: marocchino/sticky-pull-request-comment@v2
    with:
      header: Changelog
      message: ${{ steps.release.outputs.changelog }}
    if: steps.release.outputs.changelog != ''
    needs: release-please
