name: Snyk Full Scan 


on:
  push:
    branches:
      - feature/169/problem-in-appoloserver-introspection-enabled
  workflow_dispatch:

jobs:
  snyk:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Clean install dependencies
        run: npm ci

      - name: Snyk Open Source + License scan
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: test --license 

      - name: Snyk Code (SAST)
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: code test

      - name: Build Docker image
        run: docker build -t lf-admin:latest .

      - name: Snyk Container scan
        uses: snyk/actions/docker@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          image: lf-admin:latest
          args: --file=Dockerfile 
